version: '3.8'

services:
  face-recognition:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - GIN_MODE=release
    restart: unless-stopped
